### PR TITLE
5.0.0 Release

### PR DESCRIPTION
**Pull request by nblumhardt**
* #123 - update sourcelink support (@maciejw)
 * #166 - support C# 8 nullable reference types; update targets/dependencies (fixing #104) (@rafaelsc)
 * #141 - allow composition of `FileLifecycleHooks` (@EamonHetherton)
 * #145 - improve docs (@cocowalla)
 * #147 - fix validation of `fileSizeLimit` (@cocowalla)
 * #167 - improve XDOCs (@rafaelsc)
 * #190 - packaging updates (@augustoproiete)
 * #189 - allow `FileLifecycleHooks` to observe opened filename (@augustoproiete)
 * #196 - log to `SelLog` when path rolling fails (@pvandervelde)
 * #222 - remove unnecessary dependencies (@bdovaz)
 * #227 - unpin the assembly version (@nblumhardt)
 * #210 - allow `FileLifecycleHooks` to (attempt to) set the underlying stream's length (@augustoproiete)

### CODE REVIEW

**Comment by tkrafael** [comment]
Can you please check for this PR: https://github.com/serilog/serilog-sinks-file/pull/204
I've made the merge and ran all tests successfully.

**Comment by nblumhardt** [comment]
Okay, folks, [5.0.0-dev-00935](https://www.nuget.org/packages/Serilog.Sinks.File/5.0.0-dev-00935) should be the last preview package for this release!

It will need some smoke testing - if you have an app or package that depends on this sink and can try it out, 👍  or 👎  appreciated 😁 .

**Comment by Numpsy** [comment]
Is the ```Serilog.Sinks.File``` nuget package supposed to reference the ```Nullable``` nuget package, or should it just be a dev dependency?

(The Nullable docs at https://github.com/manuelroemer/Nullable#quickstart suggest that the PackageReference in the consuming project should have ```PrivateAssets="all"``` set to avoid that happening but the File sink project here doesn't do that (it does for the Sourcelink reference which is a similar build-time dependency))

**Comment by nblumhardt** [comment]
@Numpsy nice spotting, thanks!

**Pull request merged**
