### PR TITLE
Changed the UTF Encoding instance to avoid inserting the BOM character

### PR DESCRIPTION
**Pull request by christianhxc**
Fix to solve issue #9

### CODE REVIEW

**Comment by christianhxc** [comment]
@nblumhardt it seems that this won't be possible for now, look https://github.com/dotnet/coreclr/issues/5000

**Comment by nblumhardt** [comment]
Thanks Christian!

I don't think that the linked issue is the problem here, the compiler error is:

```
C:\projects\serilog-sinks-file\src\Serilog.Sinks.File\Sinks\File\FileSink.cs(59,71): error CS0246: The type or namespace name 'UTF8Encoding' could not be found (are you missing a using directive or an assembly reference?)
```

If the constructor accepting `bool` isn't present, the issue suggests that `new UTF8Encoding()` will do as we desire - a conditional compilation directive would cover both platforms in that case.

**Comment by christianhxc** [comment]
@nblumhardt still not working, that constructor doesn't exist anymore

**Comment by nblumhardt** [comment]
The package:

```json
        "System.Text.Encoding.Extensions": "4.0.11"
```

needs to be added to the netstandard1.3 dependency group for the `UTF8Encoding` type to appear.

Just a thought, shall we write it as:

```csharp
new UTF8Encoding(encoderShouldEmitUTF8Identifier: false)
```

I.e., name the parameter so that there's absolutely no ambiguity?

The above works without any conditional compilation, so seems like the way to go :+1:

**Comment by christianhxc** [comment]
@nblumhardt not sure what happened but yesterday I just tried the same thing and it didn't work (guess it was my workstation). Anyways, I already submitted the change here, I'm gonna do it for the RollingFile project :)

**Comment by nblumhardt** [comment]
Thanks @christianhxc, great stuff :-)

**Pull request merged**
