### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by sungam3r**
Use `Hide whitespaces` option. No actual code changes.

### CODE REVIEW

**Comment by bartelink** [comment]
@nblumhardt @augustoproiete would we merge a rebase of this? (If not, please close it)

**Comment by sungam3r** [comment]
Rebased.

**Comment by Numpsy** [comment]
Is this going anywhere? (It might conflict with a separate PR to update to Serilog 4 otherwise?)

**Comment by nblumhardt** [comment]
I think this should be good to build on, so I've merged; thanks @sungam3r :+1:

**Pull request merged**
